name: "Task"
description: "Feladat sablon"
title: "[Task] <Feladat rövid címe>"
body:
  - type: textarea
    id: goal
    attributes:
      label: "Cél / Leírás"
      description: "Mit kell elérni ezzel a feladattal? (1-2 mondat)"
      placeholder: "Pl. Főmenü mockup elkészítése a style guide alapján"

  - type: dropdown
    id: priority
    attributes:
      label: "Prioritás"
      options:
        - High – Kritikus
        - Medium – Fontos, de később is jöhet
        - Low – Nice to have / polish
    validations:
      required: true

  - type: textarea
    id: deliverable
    attributes:
      label: "Deliverable (Leadandó eredmény)"
      description: "Mit kell leadni / megmutatni, ami bizonyítja, hogy a feladat elkészült?"
      placeholder: "Pl. Figma-fájl a főmenüről, PDF GDD-vázlat, assetlist táblázat stb."

  - type: textarea
    id: dod
    attributes:
      label: "Definition of Done (DoD)"
      description: "Pontosan mikor számít késznek? Add meg a készültségi feltételeket."
      placeholder: |
        - Tartalmazza az összes menüpontot
        - Csapat review megtörtént
        - Verzió feltöltve a Drive-ra

  - type: textarea
    id: notes
    attributes:
      label: "Megjegyzések / Extra infó"
      description: "Egyéb részletek, referenciák, linkek"
